version: '3.8'

services:
  db:
    image: mysql:9.2.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ondepassa_db
      MYSQL_USER: admin_lp
      MYSQL_PASSWORD: admin@123
    ports:
      - "3308:3306"
    networks:
      - ondepassa-network
    volumes:
      - mysql_data:/var/lib/mysql

  ondepassa:
    image: edderluanps/ondepassa
    restart: always
    build: .
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ondepassa_db
      SPRING_DATASOURCE_USERNAME: admin_lp
      SPRING_DATASOURCE_PASSWORD: admin@123
      SPRING_FLYWAY_ENABLED: 'true'
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: 'true'
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_JPA_HIBERNATE_DDL_AUTO: 'none'
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: c3VhY2hhbGxvY2Fsa2lqay5hY2thd3F5dGl0YT1wYXNoX1ZhbGlkYXJ2b3Nl
      JWT_EXPIRATION: 43200000
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - ondepassa-network

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - ondepassa-network

volumes:
  portainer_data:
  mysql_data:

networks:
  ondepassa-network:
    driver: bridge
