INSERT INTO `tbl_liga` (`id`, `local`, `nome`) VALUES
(1, 'Inglaterra', 'Premier League 24/25'),
(2, 'Inglaterra', 'EFL Championship'),
(3, 'Espanha', 'La Liga'),
(4, 'Alemanha', 'Bundesliga'),
(5, 'Itália', 'Serie A'),
(6, 'França', 'Ligue 1'),
(7, 'Estados Unidos', 'MLS'),
(8, 'Brasil', 'Brasileirão Série A'),
(9, 'Estados Unidos', 'NBA'),
(10, 'Europa', 'EuroLeague'),
(11, 'Estados Unidos', 'NFL'),
(12, 'Canadá', 'CFL'),
(13, 'Estados Unidos', 'MLB'),
(14, 'Estados Unidos/Canadá', 'NHL'),
(15, 'Mundial', 'UFC'),
(16, 'Mundial', 'Bellator MMA'),
(17, 'Mundial', 'Formula 1'),
(18, 'Mundial', 'MotoGP'),
(19, 'Mundial', 'ATP Tour'),
(20, 'Mundial', 'WTA Tour');