spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/ondepassa_db
    password: ''
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
