spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/ondepassa_db
    password: ''
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
